### ISSUE TITLE
Layout/TrailingEmptyLines causes an infinite loop

### ISSUE THREAD

**Issue by fastjames** [r7kamura/rubocop-haml#8]
Hello, and thanks for making this extension available to everyone! I wanted to report an unusual behavior that we observed today when we ran rubocop with this extension for the first time. I saw a large number of [Layout/TrailingEmptyLines](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Layout/TrailingEmptyLines) violations, far more than the number of files in the project. It appeared to alert any time there was a line that returned a value (i.e. one that started with `=`).

I apologize for submitting an issue without having a fix PR ready to go, but I wanted to report it while the facts were still fresh in my mind.

I'm using rubocop 1.52.1.

**Comment by fastjames** [comment]
https://github.com/sds/haml-lint/issues/315 seems relevant to this issue.

**Comment by fastjames** [comment]
I see that Layout/TrailingEmptyLines is already mentioned in `config/default.yml` with the intent to exclude haml files from that cop, so I'm not sure why it is still alerting in my project.

**Comment by r7kamura** [comment]
Thanks for reporting @fastjames.

Could you please tell me the contents of your project's .rubocop.yml? Perhaps you have unexpectedly re-included `Layout/TrailingEmptyLines` in .rubocop.yml or .rubocop_todo.yml?

For example, if you have that cop excluded in .rubocop_todo.yml, adding the following setting may solve the problem.

```yaml
# .rubocop.yml
inherit_mode:
  merge:
    - Exclude
```

**Comment by fastjames** [comment]
> Thanks for reporting @fastjames.
> 
> Could you please tell me the contents of your project's .rubocop.yml? Perhaps you have unexpectedly re-included `Layout/TrailingEmptyLines` in .rubocop.yml or .rubocop_todo.yml?
> 
> For example, if you have that cop excluded in .rubocop_todo.yml, adding the following setting may solve the problem.
> 
> ```yaml
> # .rubocop.yml
> inherit_mode:
>   merge:
>     - Exclude
> ```

Thanks for that detail -- I do in fact have `Layout/TrailingEmptyLines` excluded in .rubocop_todo.yml!

**Comment by fastjames** [comment]
Applying the change that you suggested to my rubocop config resolved the problem. Thanks for the fast reply!
